# Generated by Django 3.0.7 on 2020-06-17 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='header',
            field=models.CharField(default='Welcome!', max_length=100),
            preserve_default=False,
        ),
    ]
