# Generated by Django 3.0.7 on 2020-06-17 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_home_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='header_img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
