# Generated by Django 3.0.7 on 2020-06-17 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_home_header_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='header_img',
        ),
    ]
