# Generated by Django 3.0.7 on 2020-06-17 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_home_header_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='headshot',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
